#!/usr/bin/env bash
# Main script for sourcing other bspwm configs.

# Autostart
source $HOME/.config/aperture-linux/configs/bspwm/autostart
# Settings
source $HOME/.config/aperture-linux/configs/bspwm/settings
# Rules
source $HOME/.config/aperture-linux/configs/bspwm/rules