#!/usr/bin/env bash
# Main script for sourcing other bspwm configs.

# Autostart
    ${$HOME/.config/aperture-linux/configs/bspwm/autostart}
# Settings
    ${$HOME/.config/aperture-linux/configs/bspwm/settings}
# Rules
    ${$HOME/.config/aperture-linux/configs/bspwm/rules}