#!/usr/bin/env bash

# --{{{ Call Files
  # Pywal
    ${$HOME/.cache/wal/colors.sh}
  # Example
  #source path/to/the/example
# }}}--

# --{{{ Common settings
  # check the bspc manpage for more info.

  # -( Colors values
    #bspc config normal_border_color          "#RRGGBB"                         # Color of the border of an unfocused window.
    #bspc config active_border_color          "#RRGGBB"                         # Color of the border of a focused window of an unfocused monitor.
    #bspc config focused_border_color         "#RRGGBB"                         # Color of the border of a focused window of a focused monitor.
    #bspc config presel_feedback_color        "#RRGGBB"                         # Color of the node --presel-{dir,ratio} message feedback area.
  # )-

  # -( Global rules
    #bspc config presel_feedback              false                             # Draw the preselection feedback area. Defaults to true.
    bspc config borderless_monocle            true                              # Remove borders of tiled windows for the monocle desktop layout.
    bspc config gapless_monocle               true                              # Remove gaps of tiled windows for the monocle desktop layout.
    bspc config single_monocle                true                              # Set the desktop layout to monocle if there’s only one tiled window in the tree.
    bspc config focus_follows_pointer         true                              # Focus the window under the pointer.
    #bspc config pointer_follows_focus        false                             # When focusing a window, put the pointer at its center.
    #bspc config pointer_follows_monitor      false                             # When focusing a monitor, put the pointer at its center.
    #bspc config center_pseudo_tiled          false                             # Center pseudo tiled windows into their tiling rectangles. Defaults to true.
    bspc config honor_size_hints              false                             # Apply ICCCM window size hints. (resize to the limit set by the app, beyond that point, the grid brokes)
    bspc config remove_disabled_monitors      true                              # Consider disabled monitors as disconnected.
    bspc config remove_unplugged_monitors     true                              # Remove unplugged monitors.
    #bspc config center_pseudo_tiled          true                              # Center pseudo tiled windows into their tiling rectangles. Defaults to true.
  # )-

  # -( Monitor/Desktop values
    bspc config window_gap                    10                                # Size of the gap that separates windows.
    bspc config border_width                  2                                 # Window border width.
    bspc config split_ratio                   0.50                              # Default split ratio. (0.50 = center split)
    bspc monitor -d                           1 2 3 4 5 6 7 8 9                 # Number of workspaces.
    #bspc config top_monocle_padding          0                                 # Padding space added at the sides of the screen for the monocle desktop layout.
    #bspc config right_monocle_padding        0                                 # Padding space added at the sides of the screen for the monocle desktop layout.
    #bspc config bottom_monocle_padding       0                                 # Padding space added at the sides of the screen for the monocle desktop layout.
    #bspc config left_monocle_padding         0                                 # Padding space added at the sides of the screen for the monocle desktop layout.
    #bspc config top_padding                  0                                 # Padding space added at the sides of the monitor or desktop.
    #bspc config right_padding                0                                 # Padding space added at the sides of the monitor or desktop.
    #bspc config bottom_padding               0                                 # Padding space added at the sides of the monitor or desktop.
    #bspc config left_padding                 0                                 # Padding space added at the sides of the monitor or desktop.

  # )-
# }}}--

# --{{{ Custom Settings:
  # Remember to disable the previous values that are called here. (This section will be overrided if not) 

  # -( Auto color bspwm
    THEME=$(cat "$HOME"/.config/aperture-linux/scripts/themes/tmp/current)
    if [[ "$THEME" = "cm" ]]; then
      bspc config focused_border_color "$color5" && bspc config presel_feedback_color "$color5"
    else
      bspc config focused_border_color "#F8AD19" && bspc config presel_feedback_color "#F8AD19"
    fi
  # )-
  
# }}}--
